#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, I2C_1,  leftBottomLiftEncoder, sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_2,  rightBottomLiftEncoder, sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_3,  leftTopLiftEncoder, sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_4,  rightTopLiftEncoder, sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port2,           leftBottomLift, tmotorVex393_MC29, openLoop, encoderPort, I2C_1)
#pragma config(Motor,  port3,           rightBottomLift, tmotorVex393_MC29, openLoop, reversed, encoderPort, I2C_2)
#pragma config(Motor,  port4,           leftTopLift,   tmotorVex393_MC29, openLoop, encoderPort, I2C_3)
#pragma config(Motor,  port5,           rightTopLift,  tmotorVex393_MC29, openLoop, reversed, encoderPort, I2C_4)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{

	const float bKP = 1;
	const float bKI = 1;
	const float bKD = 1;

	const float tKP = 1;
	const float tKI = 1;
	const float tKD = 1;

	const int cycleTime = 15;

	static int bottomEncoderValue, topEncoderValue;

	static int bottomSetPoint, changeInBottomSetPoint, bottomError, bottomPrevError, bottomIntegral, bottomDerivative;
	static int topSetPoint, changeInTopSetPoint, topError, topPrevError, topIntegral, topDerivative;

	static int bottomSpeed, topSpeed;

	SensorValue[leftBottomLiftEncoder] = 0;
	SensorValue[rightBottomLiftEncoder] = 0;
	SensorValue[leftTopLiftEncoder] = 0;
	SensorValue[rightTopLiftEncoder] = 0;

	while(true)
	{

		bottomEncoderValue = ((SensorValue[leftBottomLiftEncoder]) + (SensorValue[rightBottomLiftEncoder])) / 2;
		bottomSetPoint += vexRT[Ch3];
		bottomError = bottomSetPoint - bottomEncoderValue;
		bottomIntegral = bottomIntegral + bottomError;
		bottomDerivative = bottomError - bottomPrevError;
		bottomPrevError = bottomError;
		bottomSpeed = (bottomError * bKP) + (bottomIntegral * bKI) + (bottomDerivative * bKD);

		if(fabs(bottomSpeed) < 0) { bottomSpeed = 0; }
		if(fabs(bottomSpeed) > 127) { bottomSpeed = 127; }

		motor[leftBottomLift] = bottomSpeed;
		motor[rightBottomLift] = bottomSpeed;

		wait1Msec(cycleTime);

	}

}
